version: '3.5'

services:
  node1:
    container_name: node1
    volumes:
      - ../:/apps/push-env
      - ~/docker-environments:/root/docker-environments
    build: 
      context: .
    restart: always
